// Code generated by hero.
// source: http-file-upload-download/template/upload.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func PageUpload(buffer *bytes.Buffer) {
	buffer.WriteString(`<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="shortcut icon" href="/asset/favicon.ico">
<!-- <link rel="shortcut icon" type="image/x-icon" href="/asset/favicon.ico"> -->
<!-- <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/asset/favicon.ico"> -->
    <link rel="mask-icon" color="black" href="/asset/miao.svg">
    <link rel="apple-touch-icon" href="/asset/miao.png">
    <link rel="Bookmark" href="/asset/miao.png" />

    <script src="/asset/vue.min.js"></script>
    <link rel="stylesheet" href="/asset/element-ui/lib/theme-chalk/index.css">
    <script src="/asset/element-ui/lib/index.js"></script>
</head>
<body>
`)

	activeIndex := 2

	buffer.WriteString(`<div id="mushroom-nav">
    <el-menu :default-active="activeIndex" class="el-menu-demo" mode="horizontal" @select="handleSelect">
        <el-menu-item index="1"><i class="el-icon-document"></i></el-menu-item>
        <el-menu-item index="2"><i class="el-icon-document-add"></i></el-menu-item>
        <el-menu-item index="3"><i class="el-icon-edit-outline"></i></el-menu-item>
        <el-menu-item index="4" disabled><i class="el-icon-picture-outline"></i></el-menu-item>
    </el-menu>
</div>

<script>
    "use strict";
    let urlMap = {};
    urlMap['1'] = '/mushroom/';
    urlMap['2'] = '/up';
    urlMap['3'] = '/text';

    let extData = {
        data() {
            return {
                activeIndex: '`)
	hero.FormatInt(int64(activeIndex), buffer)
	buffer.WriteString(`',
            };
        },
        methods: {
            handleSelect(key, keyPath) {
                console.log(key, keyPath);
                if (urlMap.hasOwnProperty(key)) {
                    console.log(urlMap[key]);
                    window.location.href = urlMap[key];
                }
            }
        }
    };
    let navMenuCtor = Vue.extend(extData);
    new navMenuCtor().$mount('#mushroom-nav');
</script>`)
	buffer.WriteString(`
<br />
`)
	buffer.WriteString(`<div id="mushroom-upload">
    <el-upload
            class="upload-demo"
            ref="upload"
            drag
            multiple
            action="/upload/"
            :auto-upload="true">
        <i class="el-icon-upload"></i>
        <div class="el-upload__text">将文件拖到此处，或<em>点击选择文件</em></div>
    </el-upload>
</div>

<script>
    "use strict";
    let uploadExtData = {
        data() {
            return {};
        },
        methods: {
            submitUpload() {
                this.$refs.upload.submit();
            },
        }
    };
    let uploadPageCtor = Vue.extend(uploadExtData);
    new uploadPageCtor().$mount('#mushroom-upload');
    document.getElementsByTagName("title")[0].innerText = "🚀";
</script>

<style scoped>
    .el-upload {
        width: 100%;
        height: 512px;
    }

    .el-upload-dragger {
        width: 100%;
        height: 100%;
        border: 2px dashed #d9d9d9;
    }

    .el-upload-dragger .el-icon-upload {
        font-size: 256px;
        line-height: 100%;
    }

    .el-upload-dragger .el-upload__text {
        font-size: 32px;
    }
</style>
`)
	buffer.WriteString(`</body>
</html>`)

}
